enchant:
  #Enchant name (with color code)
  #For item to apply the effect it has to have a line of lore EXACTLY as here.
  #You can use multiple lore lines, just one of them has to match.
  #You can have multiple effects on 1 item.
  ยง7Slow I:
    #effect to apply on victim (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffectType.html#SPEED)
    effect: "SLOW"
    #effect multiplier
    level: 2
    #duration in ticks (20 ticks is 1 second)
    duration: 20
  ยง7Absorption:
    effect: "ABSORPTION"
    level: 1
    duration: 100
messages:
  no-permission: "You don't have permission to do this."
  wrong-argument: "There is no such subcommand."
  config-reloaded: "Config reloaded!"